/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JInternalFrame;
import javax.swing.JTextField;

/**
 *
 * @author tiago.lucas
 */
public class Agenda extends javax.swing.JFrame {

    /**
     * Creates new form Agenda
     */
    public Agenda() {
        initComponents();
    }

    private final JInternalFrame jif[] = new JInternalFrame[4];
    private final JTextField jtf[][] = new JTextField[2][5];
    private String nomePesquisado;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuItem1 = new javax.swing.JMenuItem();
        quadroInserir = new javax.swing.JInternalFrame();
        lblNome = new javax.swing.JLabel();
        txtIdadeInserir = new javax.swing.JTextField();
        lblIdade = new javax.swing.JLabel();
        txtEnderecoInserir = new javax.swing.JTextField();
        lblEndereco = new javax.swing.JLabel();
        txtCelularInserir = new javax.swing.JTextField();
        lblTelefone = new javax.swing.JLabel();
        txtNomeInserir = new javax.swing.JTextField();
        lblCelular = new javax.swing.JLabel();
        txtTelefoneInserir = new javax.swing.JTextField();
        btnCadastrar = new javax.swing.JButton();
        btnCancelarInserir = new javax.swing.JButton();
        quadroDeletar = new javax.swing.JInternalFrame();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNomeDeletar = new javax.swing.JTextField();
        txtTelefoneDeletar = new javax.swing.JTextField();
        btnDeletar = new javax.swing.JButton();
        btnCancelarDel = new javax.swing.JButton();
        quadroConsultar = new javax.swing.JInternalFrame();
        lblNome1 = new javax.swing.JLabel();
        txtIdadeConsultar = new javax.swing.JTextField();
        lblIdade1 = new javax.swing.JLabel();
        txtEnderecoConsultar = new javax.swing.JTextField();
        lblEndereco1 = new javax.swing.JLabel();
        txtCelularConsultar = new javax.swing.JTextField();
        lblTelefone1 = new javax.swing.JLabel();
        txtNomeConsultar = new javax.swing.JTextField();
        lblCelular1 = new javax.swing.JLabel();
        txtTelefoneConsultar = new javax.swing.JTextField();
        btnConsulta = new javax.swing.JButton();
        btnCancelarInserir1 = new javax.swing.JButton();
        quadroAlterar = new javax.swing.JInternalFrame();
        lblNome2 = new javax.swing.JLabel();
        txtIdadeAlterar = new javax.swing.JTextField();
        lblIdade2 = new javax.swing.JLabel();
        txtEnderecoAlterar = new javax.swing.JTextField();
        lblEndereco2 = new javax.swing.JLabel();
        txtCelularAlterar = new javax.swing.JTextField();
        lblTelefone2 = new javax.swing.JLabel();
        txtNomeAlterar = new javax.swing.JTextField();
        lblCelular2 = new javax.swing.JLabel();
        txtTelefoneAlterar = new javax.swing.JTextField();
        btnAlterar = new javax.swing.JButton();
        btnCancelarInserir2 = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        inserirContato = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        deletarContato = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        menuAlterar = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        jButton1.setText("jButton1");

        jLabel1.setText("jLabel1");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(400, 300));
        setMinimumSize(new java.awt.Dimension(400, 300));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        quadroInserir.setBackground(new java.awt.Color(204, 204, 204));
        quadroInserir.setBorder(null);
        quadroInserir.setVisible(false);

        lblNome.setText("Nome:");

        lblIdade.setText("Idade:");

        lblEndereco.setText("Endereço:");

        lblTelefone.setText("Telefone:");

        lblCelular.setText("Celular:");

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        btnCancelarInserir.setText("Cancelar");
        btnCancelarInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarInserirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout quadroInserirLayout = new javax.swing.GroupLayout(quadroInserir.getContentPane());
        quadroInserir.getContentPane().setLayout(quadroInserirLayout);
        quadroInserirLayout.setHorizontalGroup(
            quadroInserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quadroInserirLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(quadroInserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(quadroInserirLayout.createSequentialGroup()
                        .addGroup(quadroInserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNome)
                            .addComponent(lblIdade))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(quadroInserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNomeInserir, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addComponent(txtIdadeInserir)))
                    .addGroup(quadroInserirLayout.createSequentialGroup()
                        .addGroup(quadroInserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEndereco)
                            .addComponent(lblTelefone)
                            .addComponent(lblCelular))
                        .addGap(52, 52, 52)
                        .addGroup(quadroInserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTelefoneInserir, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtEnderecoInserir)
                            .addComponent(txtCelularInserir))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, quadroInserirLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancelarInserir)
                .addGap(18, 18, 18)
                .addComponent(btnCadastrar)
                .addGap(28, 28, 28))
        );
        quadroInserirLayout.setVerticalGroup(
            quadroInserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, quadroInserirLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(quadroInserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(txtNomeInserir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(quadroInserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdade)
                    .addComponent(txtIdadeInserir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(quadroInserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEndereco)
                    .addComponent(txtEnderecoInserir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(quadroInserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefone)
                    .addComponent(txtTelefoneInserir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(quadroInserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCelular)
                    .addComponent(txtCelularInserir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(quadroInserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelarInserir)
                    .addComponent(btnCadastrar))
                .addGap(69, 69, 69))
        );

        quadroDeletar.setBackground(new java.awt.Color(204, 204, 204));
        quadroDeletar.setBorder(null);
        quadroDeletar.setVisible(false);

        jLabel2.setText("Nome:");

        jLabel3.setText("Telefone:");

        btnDeletar.setText("Deletar");
        btnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarActionPerformed(evt);
            }
        });

        btnCancelarDel.setText("Cancelar");
        btnCancelarDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarDelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout quadroDeletarLayout = new javax.swing.GroupLayout(quadroDeletar.getContentPane());
        quadroDeletar.getContentPane().setLayout(quadroDeletarLayout);
        quadroDeletarLayout.setHorizontalGroup(
            quadroDeletarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quadroDeletarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(quadroDeletarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(quadroDeletarLayout.createSequentialGroup()
                        .addGroup(quadroDeletarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(quadroDeletarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNomeDeletar)
                            .addComponent(txtTelefoneDeletar)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, quadroDeletarLayout.createSequentialGroup()
                        .addGap(0, 168, Short.MAX_VALUE)
                        .addComponent(btnCancelarDel)
                        .addGap(18, 18, 18)
                        .addComponent(btnDeletar)))
                .addContainerGap())
        );
        quadroDeletarLayout.setVerticalGroup(
            quadroDeletarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quadroDeletarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(quadroDeletarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNomeDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(quadroDeletarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTelefoneDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(quadroDeletarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeletar)
                    .addComponent(btnCancelarDel))
                .addContainerGap(131, Short.MAX_VALUE))
        );

        quadroConsultar.setBackground(new java.awt.Color(204, 204, 204));
        quadroConsultar.setBorder(null);
        quadroConsultar.setVisible(false);

        lblNome1.setText("Nome:");

        txtIdadeConsultar.setEditable(false);
        txtIdadeConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdadeConsultarActionPerformed(evt);
            }
        });

        lblIdade1.setText("Idade:");

        txtEnderecoConsultar.setEditable(false);

        lblEndereco1.setText("Endereço:");

        txtCelularConsultar.setEditable(false);

        lblTelefone1.setText("Telefone:");

        lblCelular1.setText("Celular:");

        txtTelefoneConsultar.setEditable(false);

        btnConsulta.setText("Consultar");
        btnConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaActionPerformed(evt);
            }
        });

        btnCancelarInserir1.setText("Cancelar");
        btnCancelarInserir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarInserir1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout quadroConsultarLayout = new javax.swing.GroupLayout(quadroConsultar.getContentPane());
        quadroConsultar.getContentPane().setLayout(quadroConsultarLayout);
        quadroConsultarLayout.setHorizontalGroup(
            quadroConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quadroConsultarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(quadroConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(quadroConsultarLayout.createSequentialGroup()
                        .addGroup(quadroConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNome1)
                            .addComponent(lblIdade1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(quadroConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNomeConsultar, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addComponent(txtIdadeConsultar)))
                    .addGroup(quadroConsultarLayout.createSequentialGroup()
                        .addGroup(quadroConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEndereco1)
                            .addComponent(lblTelefone1)
                            .addComponent(lblCelular1))
                        .addGap(52, 52, 52)
                        .addGroup(quadroConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTelefoneConsultar, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtEnderecoConsultar)
                            .addComponent(txtCelularConsultar))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, quadroConsultarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancelarInserir1)
                .addGap(18, 18, 18)
                .addComponent(btnConsulta)
                .addGap(28, 28, 28))
        );
        quadroConsultarLayout.setVerticalGroup(
            quadroConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, quadroConsultarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(quadroConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome1)
                    .addComponent(txtNomeConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(quadroConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdade1)
                    .addComponent(txtIdadeConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(quadroConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEndereco1)
                    .addComponent(txtEnderecoConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(quadroConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefone1)
                    .addComponent(txtTelefoneConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(quadroConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCelular1)
                    .addComponent(txtCelularConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(quadroConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelarInserir1)
                    .addComponent(btnConsulta))
                .addGap(69, 69, 69))
        );

        quadroAlterar.setBackground(new java.awt.Color(204, 204, 204));
        quadroAlterar.setBorder(null);
        quadroAlterar.setVisible(false);
        quadroAlterar.addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                quadroAlterarInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        lblNome2.setText("Nome:");

        txtIdadeAlterar.setEditable(false);

        lblIdade2.setText("Idade:");

        txtEnderecoAlterar.setEditable(false);

        lblEndereco2.setText("Endereço:");

        txtCelularAlterar.setEditable(false);

        lblTelefone2.setText("Telefone:");

        lblCelular2.setText("Celular:");

        txtTelefoneAlterar.setEditable(false);

        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnCancelarInserir2.setText("Cancelar");
        btnCancelarInserir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarInserir2ActionPerformed(evt);
            }
        });

        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout quadroAlterarLayout = new javax.swing.GroupLayout(quadroAlterar.getContentPane());
        quadroAlterar.getContentPane().setLayout(quadroAlterarLayout);
        quadroAlterarLayout.setHorizontalGroup(
            quadroAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quadroAlterarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(quadroAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(quadroAlterarLayout.createSequentialGroup()
                        .addGroup(quadroAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNome2)
                            .addComponent(lblIdade2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(quadroAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNomeAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addComponent(txtIdadeAlterar)))
                    .addGroup(quadroAlterarLayout.createSequentialGroup()
                        .addGroup(quadroAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEndereco2)
                            .addComponent(lblTelefone2)
                            .addComponent(lblCelular2))
                        .addGap(52, 52, 52)
                        .addGroup(quadroAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTelefoneAlterar, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtEnderecoAlterar)
                            .addComponent(txtCelularAlterar))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, quadroAlterarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnConsultar)
                .addGap(18, 18, 18)
                .addComponent(btnCancelarInserir2)
                .addGap(18, 18, 18)
                .addComponent(btnAlterar)
                .addGap(28, 28, 28))
        );
        quadroAlterarLayout.setVerticalGroup(
            quadroAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, quadroAlterarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(quadroAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome2)
                    .addComponent(txtNomeAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(quadroAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdade2)
                    .addComponent(txtIdadeAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(quadroAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEndereco2)
                    .addComponent(txtEnderecoAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(quadroAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefone2)
                    .addComponent(txtTelefoneAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(quadroAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCelular2)
                    .addComponent(txtCelularAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(quadroAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelarInserir2)
                    .addComponent(btnAlterar)
                    .addComponent(btnConsultar))
                .addGap(69, 69, 69))
        );

        jMenu3.setText("Inserir");

        inserirContato.setText("Contato");
        inserirContato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inserirContatoActionPerformed(evt);
            }
        });
        jMenu3.add(inserirContato);

        jMenuBar1.add(jMenu3);

        jMenu1.setText("Deletar");

        deletarContato.setText("Contato");
        deletarContato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletarContatoActionPerformed(evt);
            }
        });
        jMenu1.add(deletarContato);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Consultar");

        jMenuItem2.setText("Contato");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        menuAlterar.setText("Alterar");

        jMenuItem3.setText("Contato");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        menuAlterar.add(jMenuItem3);

        jMenuBar1.add(menuAlterar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(quadroInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(quadroDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(quadroConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(quadroAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(quadroInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(quadroAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(quadroConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(quadroDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * lógica para transferir os JInternalFrame para arrays
     */
    public void montarJif() {
        jif[0] = quadroInserir;
        jif[1] = quadroDeletar;
        jif[2] = quadroConsultar;
        jif[3] = quadroAlterar;
    }

    /**
     * Lógica para montar o quadro (JInternalFrame) clicado na agenda e ao mesmo
     * tempo desmontar os outros quadros. Não é possível mostrar mais de um
     * quadro ao mesmo tempo.
     *
     * @param id
     */
    public void montarQuadroJif(int id) {
        montarJif();
        for (int i = 0; i < 4; i++) {
            if (i != id) {
                jif[i].setVisible(false);
                jif[i].dispose();
            } else {
                jif[i].setVisible(true);
                jif[i].setSize(421, 339);
                switch (i) {
                    case 0:
                        jif[i].setTitle("Inserir Contato");
                        break;
                    case 1:
                        jif[i].setTitle("Deletar Contato");
                        break;
                    case 2:
                        jif[i].setTitle("Consultar Contato");
                        break;
                    case 3:
                        jif[i].setTitle("Alterar Contato");
                        break;
                }
            }
        }
    }
/**
 * Lógica para transferir os JTextField para arrays
 */
    public void montarTxt() {
        jtf[0][0] = txtCelularAlterar;
        jtf[0][1] = txtEnderecoAlterar;
        jtf[0][2] = txtIdadeAlterar;
        jtf[0][3] = txtNomeAlterar;
        jtf[0][4] = txtTelefoneAlterar;
        jtf[1][0] = txtCelularConsultar;
        jtf[1][1] = txtEnderecoConsultar;
        jtf[1][2] = txtIdadeConsultar;
        jtf[1][3] = txtNomeConsultar;
        jtf[1][4] = txtTelefoneConsultar;
    }


    private void inserirContatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inserirContatoActionPerformed
        montarQuadroJif(0);
    }//GEN-LAST:event_inserirContatoActionPerformed

    private void deletarContatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletarContatoActionPerformed
        montarQuadroJif(1);
    }//GEN-LAST:event_deletarContatoActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

    }//GEN-LAST:event_formWindowOpened

    private void btnCancelarInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarInserirActionPerformed
        // TODO add your handling code here:
        quadroInserir.dispose();
    }//GEN-LAST:event_btnCancelarInserirActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        Controller.Controlador control = new Controller.Controlador();
        try {
            control.inserirContato(txtNomeInserir.getText(), Integer.parseInt(txtIdadeInserir.getText()), txtEnderecoInserir.getText(), txtTelefoneInserir.getText(), txtCelularInserir.getText());
            // TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(Agenda.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaActionPerformed
        Controller.Controlador control = new Controller.Controlador();
        ResultSet rs = control.consultarContato(txtNomeConsultar.getText());
        preenchendoCampos(rs, 0);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnConsultaActionPerformed

    /**
     * Preenchimento dos JTextField. O id serve para diferenciar
     * entre Consulta e Alteração
     * @param rs
     * @param id 
     * @return 
     */
    private boolean preenchendoCampos(ResultSet rs, int id) {
        if (id == 0) {
            try {
                rs.first();
                txtCelularConsultar.setText(rs.getString("celular"));
                txtEnderecoConsultar.setText(rs.getString("endereco"));
                txtIdadeConsultar.setText(rs.getString("idade"));
                txtNomeConsultar.setText(rs.getString("nome"));
                txtTelefoneConsultar.setText(rs.getString("telefone"));
                return true;
            } catch (SQLException ex) {
                System.out.println("Não recuperado: " + ex);
                return false;
            }
        } else {
            try {
                rs.first();
                txtCelularAlterar.setText(rs.getString("celular"));
                txtEnderecoAlterar.setText(rs.getString("endereco"));
                txtIdadeAlterar.setText(rs.getString("idade"));
                txtNomeAlterar.setText(rs.getString("nome"));
                txtTelefoneAlterar.setText(rs.getString("telefone"));
                return true;
            } catch (SQLException ex) {
                System.out.println("Não recuperado: " + ex);
                return false;
            }
        }

    }

    private void btnCancelarInserir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarInserir1ActionPerformed
        quadroConsultar.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarInserir1ActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        Controller.Controlador control = new Controller.Controlador();
        control.alterarContato(txtNomeAlterar.getText(), txtIdadeAlterar.getText(), txtEnderecoAlterar.getText(), txtTelefoneAlterar.getText(), txtCelularAlterar.getText(),nomePesquisado);        // TODO add your handling code here:
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnCancelarInserir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarInserir2ActionPerformed
        quadroAlterar.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarInserir2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        montarQuadroJif(3);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void txtIdadeConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdadeConsultarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdadeConsultarActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        Controller.Controlador control = new Controller.Controlador();
        ResultSet rs = control.consultarContato(txtNomeAlterar.getText());
        if(preenchendoCampos(rs,1)){
            txtCelularAlterar.setEditable(true);
            txtEnderecoAlterar.setEditable(true);
            txtIdadeAlterar.setEditable(true);
            txtTelefoneAlterar.setEditable(true);
            nomePesquisado=txtNomeAlterar.getText();
        }

    }//GEN-LAST:event_btnConsultarActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        montarQuadroJif(2);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void btnCancelarDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarDelActionPerformed
        quadroDeletar.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarDelActionPerformed

    private void quadroAlterarInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_quadroAlterarInternalFrameClosed
        txtCelularAlterar.setEditable(false);
        txtEnderecoAlterar.setEditable(false);
        txtIdadeAlterar.setEditable(false);
        txtTelefoneAlterar.setEditable(false);        // TODO add your handling code here:
    }//GEN-LAST:event_quadroAlterarInternalFrameClosed

    private void btnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarActionPerformed
        Controller.Controlador control = new Controller.Controlador();
        control.deletarContato(txtNomeDeletar.getText(), txtTelefoneDeletar.getText());
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeletarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnCancelarDel;
    private javax.swing.JButton btnCancelarInserir;
    private javax.swing.JButton btnCancelarInserir1;
    private javax.swing.JButton btnCancelarInserir2;
    private javax.swing.JButton btnConsulta;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnDeletar;
    private javax.swing.JMenuItem deletarContato;
    private javax.swing.JMenuItem inserirContato;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JLabel lblCelular;
    private javax.swing.JLabel lblCelular1;
    private javax.swing.JLabel lblCelular2;
    private javax.swing.JLabel lblEndereco;
    private javax.swing.JLabel lblEndereco1;
    private javax.swing.JLabel lblEndereco2;
    private javax.swing.JLabel lblIdade;
    private javax.swing.JLabel lblIdade1;
    private javax.swing.JLabel lblIdade2;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNome1;
    private javax.swing.JLabel lblNome2;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JLabel lblTelefone1;
    private javax.swing.JLabel lblTelefone2;
    private javax.swing.JMenu menuAlterar;
    private javax.swing.JInternalFrame quadroAlterar;
    private javax.swing.JInternalFrame quadroConsultar;
    private javax.swing.JInternalFrame quadroDeletar;
    private javax.swing.JInternalFrame quadroInserir;
    private javax.swing.JTextField txtCelularAlterar;
    private javax.swing.JTextField txtCelularConsultar;
    private javax.swing.JTextField txtCelularInserir;
    private javax.swing.JTextField txtEnderecoAlterar;
    private javax.swing.JTextField txtEnderecoConsultar;
    private javax.swing.JTextField txtEnderecoInserir;
    private javax.swing.JTextField txtIdadeAlterar;
    private javax.swing.JTextField txtIdadeConsultar;
    private javax.swing.JTextField txtIdadeInserir;
    private javax.swing.JTextField txtNomeAlterar;
    private javax.swing.JTextField txtNomeConsultar;
    private javax.swing.JTextField txtNomeDeletar;
    private javax.swing.JTextField txtNomeInserir;
    private javax.swing.JTextField txtTelefoneAlterar;
    private javax.swing.JTextField txtTelefoneConsultar;
    private javax.swing.JTextField txtTelefoneDeletar;
    private javax.swing.JTextField txtTelefoneInserir;
    // End of variables declaration//GEN-END:variables
}
